added gribapi test support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1302,6 +1302,7 @@ Optional Features:
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --disable-largefile     omit support for large files
+  --enable-grib           GRIB support [default=yes]
   --enable-dap            Build OPeNDAP/DODS-enabled clients if possible
                           [default=no]
 
@@ -1318,9 +1319,17 @@ Optional Packages:
                           Specify location of SZLIB library. You must specify
                           its location if HDF5 was built with SZLIB. Configure
                           will expect to find subdirs include and lib.
+  --with-jasper=<directory>
+                          Specify location of JASPER library. You must specify
+                          its location if GRIB_API was built with JASPER.
+                          Configure will expect to find subdirs include and
+                          lib.
+  --with-grib_api=<directory>
+                          Specify location of GRIB_API library. Configure will
+                          expect to find subdirs include and lib.
   --with-hdf5=<directory> Specify location of HDF5 library. Configure will
                           expect to find subdirs include and lib.
-  --with-grib             Use the internal GRIB library [default=yes]
+  --with-cgribex          Use the GRIB library [default=yes]
   --with-service          Use the internal SERVICE library [default=yes]
   --with-extra            Use the internal EXTRA library [default=yes]
   --with-ieg              Use the internal IEG library [default=yes]
@@ -6450,6 +6459,196 @@ fi
 fi
 
 #  ----------------------------------------------------------------------
+#  Compile application with JASPER library
+#
+{ echo "$as_me:$LINENO: checking whether a location for the JASPER library was specified" >&5
+echo $ECHO_N "checking whether a location for the JASPER library was specified... $ECHO_C" >&6; }
+
+# Check whether --with-jasper was given.
+if test "${with_jasper+set}" = set; then
+  withval=$with_jasper; JASPERDIR=$with_jasper
+fi
+
+if test -z "$JASPERDIR" ; then
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+else
+  { echo "$as_me:$LINENO: result: $JASPERDIR" >&5
+echo "${ECHO_T}$JASPERDIR" >&6; }
+  LDFLAGS="$LDFLAGS -L$JASPERDIR/lib"
+  CPPFLAGS="$CPPFLAGS -I$JASPERDIR/include"
+
+{ echo "$as_me:$LINENO: checking for jas_init in -ljasper" >&5
+echo $ECHO_N "checking for jas_init in -ljasper... $ECHO_C" >&6; }
+if test "${ac_cv_lib_jasper_jas_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ljasper  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char jas_init ();
+int
+main ()
+{
+return jas_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_jasper_jas_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_jasper_jas_init=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_jasper_jas_init" >&5
+echo "${ECHO_T}$ac_cv_lib_jasper_jas_init" >&6; }
+if test $ac_cv_lib_jasper_jas_init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBJASPER 1
+_ACEOF
+
+  LIBS="-ljasper $LIBS"
+
+else
+  LDFLAGS="$LDFLAGS"
+fi
+
+# AC_SUBST([JASPERDIR], [$JASPERDIR])
+fi
+
+#  ----------------------------------------------------------------------
+#  Compile application with GRIB_API library
+#
+{ echo "$as_me:$LINENO: checking whether a location for the GRIB_API library was specified" >&5
+echo $ECHO_N "checking whether a location for the GRIB_API library was specified... $ECHO_C" >&6; }
+
+# Check whether --with-grib_api was given.
+if test "${with_grib_api+set}" = set; then
+  withval=$with_grib_api; GRIB_APIDIR=$with_grib_api
+fi
+
+if test -z "$GRIB_APIDIR" ; then
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+else
+  { echo "$as_me:$LINENO: result: $GRIB_APIDIR" >&5
+echo "${ECHO_T}$GRIB_APIDIR" >&6; }
+  LDFLAGS="$LDFLAGS -L$GRIB_APIDIR/lib"
+  CPPFLAGS="$CPPFLAGS -I$GRIB_APIDIR/include"
+
+{ echo "$as_me:$LINENO: checking for grib_get_message in -lgrib_api" >&5
+echo $ECHO_N "checking for grib_get_message in -lgrib_api... $ECHO_C" >&6; }
+if test "${ac_cv_lib_grib_api_grib_get_message+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgrib_api  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char grib_get_message ();
+int
+main ()
+{
+return grib_get_message ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_grib_api_grib_get_message=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_grib_api_grib_get_message=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_grib_api_grib_get_message" >&5
+echo "${ECHO_T}$ac_cv_lib_grib_api_grib_get_message" >&6; }
+if test $ac_cv_lib_grib_api_grib_get_message = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGRIB_API 1
+_ACEOF
+
+  LIBS="-lgrib_api $LIBS"
+
+else
+  LDFLAGS="$LDFLAGS"
+fi
+
+# AC_SUBST([GRIB_APIDIR], [$GRIB_APIDIR])
+fi
+
+#  ----------------------------------------------------------------------
 #  Compile application with HDF5 library
 #
 { echo "$as_me:$LINENO: checking whether a location for the HDF5 library was specified" >&5
@@ -6637,18 +6836,17 @@ fi
 fi
 
 #  ----------------------------------------------------------------------
-#  Compile interface with internal GRIB library
-#
+#  Enable GRIB support
 
-# Check whether --with-grib was given.
-if test "${with_grib+set}" = set; then
-  withval=$with_grib;
+# Check whether --enable-grib was given.
+if test "${enable_grib+set}" = set; then
+  enableval=$enable_grib; enable_grib=${enableval}
 else
-  with_grib="yes"
+  enable_grib=yes
 fi
 
 
-if test "${with_grib}" = "yes" ; then
+if test "${enable_grib}" = "yes"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_LIBGRIB 1
@@ -6658,8 +6856,33 @@ fi
 
 { echo "$as_me:$LINENO: checking for GRIB support" >&5
 echo $ECHO_N "checking for GRIB support... $ECHO_C" >&6; }
-{ echo "$as_me:$LINENO: result: $with_grib" >&5
-echo "${ECHO_T}$with_grib" >&6; }
+{ echo "$as_me:$LINENO: result: $enable_grib" >&5
+echo "${ECHO_T}$enable_grib" >&6; }
+
+#  ----------------------------------------------------------------------
+#  Compile interface with internal CGRIBEX library
+#
+
+# Check whether --with-cgribex was given.
+if test "${with_cgribex+set}" = set; then
+  withval=$with_cgribex;
+else
+  with_cgribex="yes"
+fi
+
+
+if test "${with_cgribex}" = "yes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBCGRIBEX 1
+_ACEOF
+
+fi
+
+{ echo "$as_me:$LINENO: checking for CGRIBEX support" >&5
+echo $ECHO_N "checking for CGRIBEX support... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: result: $with_cgribex" >&5
+echo "${ECHO_T}$with_cgribex" >&6; }
 
 #  ----------------------------------------------------------------------
 #  Compile interface with internal SERVICE library
