add support for GRID type SINUSOIDAL

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1322,6 +1322,8 @@ Optional Packages:
                           expect to find subdirs include and lib.
   --with-hdf5=<directory> Specify location of HDF5 library. Configure will
                           expect to find subdirs include and lib.
+  --with-proj=<directory> Specify location of PROJ library. Configure will
+                          expect to find subdirs include and lib.
 
 Some influential environment variables:
   AR          AR archive command
@@ -6873,7 +6875,7 @@ echo "$as_me: error: couldn't find netcdf library" >&2;}
 esac
 
 #  ----------------------------------------------------------------------
-#  Compile interface with SZLIB library
+#  Compile application with SZLIB library
 #
 { echo "$as_me:$LINENO: checking whether a location for the SZLIB library was specified" >&5
 echo $ECHO_N "checking whether a location for the SZLIB library was specified... $ECHO_C" >&6; }
@@ -6968,7 +6970,7 @@ fi
 fi
 
 #  ----------------------------------------------------------------------
-#  Compile interface with HDF5 library
+#  Compile application with HDF5 library
 #
 { echo "$as_me:$LINENO: checking whether a location for the HDF5 library was specified" >&5
 echo $ECHO_N "checking whether a location for the HDF5 library was specified... $ECHO_C" >&6; }
@@ -7060,6 +7062,101 @@ else
 fi
 
 # AC_SUBST([HDF5DIR], [$HDF5DIR])
+fi
+
+#  ----------------------------------------------------------------------
+#  Compile application with PROJ library
+#
+{ echo "$as_me:$LINENO: checking whether a location for the PROJ library was specified" >&5
+echo $ECHO_N "checking whether a location for the PROJ library was specified... $ECHO_C" >&6; }
+
+# Check whether --with-proj was given.
+if test "${with_proj+set}" = set; then
+  withval=$with_proj; PROJDIR=$with_proj
+fi
+
+if test -z "$PROJDIR" ; then
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+else
+  { echo "$as_me:$LINENO: result: $PROJDIR" >&5
+echo "${ECHO_T}$PROJDIR" >&6; }
+  LDFLAGS="$LDFLAGS -L$PROJDIR/lib"
+  CPPFLAGS="$CPPFLAGS -I$PROJDIR/include"
+
+{ echo "$as_me:$LINENO: checking for pj_init in -lproj" >&5
+echo $ECHO_N "checking for pj_init in -lproj... $ECHO_C" >&6; }
+if test "${ac_cv_lib_proj_pj_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lproj -lm $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char pj_init ();
+int
+main ()
+{
+return pj_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_proj_pj_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_proj_pj_init=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_proj_pj_init" >&5
+echo "${ECHO_T}$ac_cv_lib_proj_pj_init" >&6; }
+if test $ac_cv_lib_proj_pj_init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPROJ 1
+_ACEOF
+
+  LIBS="-lproj $LIBS"
+
+else
+  LDFLAGS="$LDFLAGS"
+fi
+
+# AC_SUBST([PROJDIR], [$PROJDIR])
 fi
 
 #  ----------------------------------------------------------------------
